### ISSUE TITLE
Updates Needed in MATLAB Implementation

### ISSUE THREAD

**Issue by hjozwiak-umk** [nikodem-stolarczyk/spectral-line-shapes#16]
## Updates Needed in MATLAB Implementation

This issue tracks necessary updates and improvements to the MATLAB implementation as discussed in recent pull requests. Please review the tasks below and check off each item as it is completed to ensure all updates are accounted for:

- [x] **Update Documentation of the mHT Function**
  - **Details**: Enhance and clarify the existing documentation, similar to the Python implementation.
  - **Related Pull Request**: #9 

- [x] **Change Default CPF Routine for mHT**
  - **Details**: Update the default CPF routine used in the mHT function to `cpf_accurate`.
  - **Related Pull Request**: #9 

- [x] **Correct Sign for Humlicek Mask**
  - **Details**: Address the incorrect sign in the Humlicek mask.
  - **Related Pull Request**: #13 

- [x] **Prepare a Usage Example**
  - **Details**: Develop a usage example similar to the Python implemenation.
  - **Related Pull Request**: #11

**Comment by SuoWick** [comment]
3/4 made.
Please state in more details the lacks of the MATLAB documentations.

**Comment by nikodem-stolarczyk** [comment]
see branch https://github.com/nikodem-stolarczyk/spectral-line-shapes/tree/nikodem-stolarczyk-patch-3-1 and take the python part of README as the example. Matlab sections are to be filled.

**Comment by SuoWick** [comment]
MATLAB readme put on hold until example structure will be sorted.
After that it will be prepared similar to python one.

**Comment by nikodem-stolarczyk** [comment]
Please solve issue: profile.m function conflicts with MATLAB's built-in "profile" function

**Comment by hjozwiak-umk** [comment]
> Please solve issue: profile.m function conflicts with MATLAB's built-in "profile" function

Please leave it as it is

**Comment by SuoWick** [comment]
Update Documentation of the mHT Function done within SuoWick-MATLAB-Refurb pull request.
